name: debug-script
on: push

jobs:
  ubuntu-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run debug script
        run: ${GITHUB_WORKSPACE}/debug.sh > debug-ubuntu.log
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: debug-logs
          path: debug-ubuntu.log

  windows-job:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run debug script
        run: ${GITHUB_WORKSPACE}/debug.sh > debug-windows.log
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: debug-logs
          path: debug-windows.log
